# NumPy Example 1
## Creating a Rank 1 **Array**

In [1]:
import numpy as np

# Create a rank 1 array
a = np.array([0, 1, 2])

print(type(a))
print(a.shape)
print(a[0])
print(a[1])
print(a[2])

# Change an element
a[0] = 5

print(a)

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


# NumPy Example 2
## Creating Different Types of **Arrays**

In [2]:
import numpy as np

# Create a 3x3 array of all zeros
a = np.zeros((3,3))
print(a)

# Create a 2x2 array of all ones
b = np.ones((2,2))
print(b)

# Create a 3x3 constant array
c = np.full((3,3), 7)
print(c)

# Create a 3x3 array filled with random values
d = np.random.random((3,3))
print(d)

# Create a 3x3 identity matrix
e = np.eye(3)
print(e)

# Convert list to array
f = np.array([2,3,1,0])
print(f)

# Create an array with values from 0 to 19
g = np.arange(20)
print(g)

# Mixed data types
h = np.array([[0,1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)

# Create an array of floats
i = np.arange(1,8,dtype=float)
print(i)

# Create 5 equally spaced numbers between 2 and 4
j = np.linspace(2,4,5)
print(j)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.81134975 0.2786307  0.9794777 ]
 [0.00297968 0.58641918 0.47275604]
 [0.44345439 0.19797513 0.52598482]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 3 1 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]
[1. 2. 3. 4. 5. 6. 7.]
[2.  2.5 3.  3.5 4. ]


# NumPy Example 3
## NumPy Data **Types**

In [3]:
import numpy as np

# Let NumPy choose the data type
x = np.array([0, 1])
y = np.array([2.0, 3.0])

# Force a particular data type
z = np.array([5, 6], dtype=np.int64)

print("x dtype:", x.dtype)
print("y dtype:", y.dtype)
print("z dtype:", z.dtype)

x dtype: int64
y dtype: float64
z dtype: int64


# NumPy Example 4
## Array **Indexing**

In [4]:
import numpy as np

# An example array
arr = np.array([
    [-1, 2, 0, 4],
    [4, -0.5, 6, 0],
    [2.6, 0, 7, 8],
    [3, -7, 4, 2.0]
])

# Slicing array
temp = arr[:2, ::2]
print("Array with first 2 rows and alternate columns (0 and 2):\n", temp)

# Integer array indexing
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print("\nElements at indices (0,3), (1,2), (2,1), (3,0):\n", temp)

# Boolean array indexing
cond = arr > 0
temp = arr[cond]
print("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternate columns (0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0,3), (1,2), (2,1), (3,0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# NumPy Example 5
## Basic Array **Operations**

In [5]:
import numpy as np

# Python program to demonstrate
# basic operations on single array

a = np.array([1, 2, 5, 3])

# Add 1 to every element
print("Adding 1 to every element:", a + 1)

# Subtract 3 from each element
print("Subtracting 3 from each element:", a - 3)

# Multiply each element by 10
print("Multiplying each element by 10:", a * 10)

# Square each element
print("Squaring each element:", a ** 2)

# Modify existing array
a *= 2
print("Doubled each element of original array:", a)

# Transpose of array
a = np.array([[1, 2, 3],
              [3, 4, 5],
              [9, 6, 0]])

print("\nOriginal array:\n", a)
print("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


# NumPy Example 6
## Unary **Operators**

In [6]:
import numpy as np

# Python program to demonstrate unary operators in NumPy

arr = np.array([
    [1, 5, 6],
    [4, 7, 2],
    [3, 1, 9]
])

# Maximum element of array
print("Largest element is:", arr.max())

# Row-wise maximum elements
print("Row-wise maximum elements:", arr.max(axis=1))

# Minimum element of array (column-wise)
print("Column-wise minimum elements:", arr.min(axis=0))

# Sum of all array elements
print("Sum of all array elements:", arr.sum())

# Cumulative sum along each row
print("Cumulative sum along each row:\n", arr.cumsum(axis=1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


# NumPy Example 7
## Binary **Operators**

In [7]:
import numpy as np

# Python program to demonstrate
# binary operators in NumPy

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[4, 3],
              [2, 1]])

# Add arrays
print("Array sum:\n", a + b)

# Multiply arrays (element-wise multiplication)
print("\nArray multiplication:\n", a * b)

# Matrix multiplication
print("\nMatrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]

Array multiplication:
 [[4 6]
 [6 4]]

Matrix multiplication:
 [[ 8  5]
 [20 13]]


# NumPy Example 8
## Universal Functions (ufunc)

In [8]:
import numpy as np

# Python program to demonstrate
# universal functions in NumPy

# Create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print("Sine values of array elements:", np.sin(a))

# Exponential values
a = np.array([0, 1, 2, 3])
print("Exponent of array elements:", np.exp(a))

# Square root values
print("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


# NumPy Example 9
## Matrix **Inverse**

In [9]:
import numpy as np

# Python program to find the inverse of a matrix

arr = np.array([
    [-1, 2, 0, 4],
    [4, -0.5, 6, 0],
    [2.6, 0, 7, 8],
    [3, -7, 4, 2.0]
])

inverse = np.linalg.inv(arr)

print("Inverse of matrix:")
print(inverse)

Inverse of matrix:
[[ 4.05707196  1.98511166 -2.28287841  1.01736973]
 [ 0.50620347  0.30272953 -0.24813896 -0.01985112]
 [-2.66253102 -1.13151365  1.50124069 -0.67990074]
 [ 1.01116625  0.34491315 -0.44665012  0.26426799]]




## Pandas Example 1

### Creating a **Series**

In [10]:
import pandas as pd
import numpy as np

# Creating a Series
s = pd.Series(
    [1, 2, 3, np.nan, 5, 6],
    index=['A', 'B', 'C', 'D', 'E', 'F']
)

print(s)

A    1.0
B    2.0
C    3.0
D    NaN
E    5.0
F    6.0
dtype: float64


## Pandas Example 2

### Creating a **DataFrame**

In [11]:
import pandas as pd

data = {
    'Gender': ['F', 'M', 'M'],
    'Emp_ID': ['E01', 'E02', 'E03'],
    'Age': [25, 27, 25]
}

# Specify the column order
df = pd.DataFrame(data, columns=['Emp_ID', 'Gender', 'Age'])

print(df)           # Print the entire DataFrame
print(df.Emp_ID)    # Print the Emp_ID column
print(df.Emp_ID[0]) # Print the first Emp_ID

  Emp_ID Gender  Age
0    E01      F   25
1    E02      M   27
2    E03      M   25
0    E01
1    E02
2    E03
Name: Emp_ID, dtype: object
E01


## Pandas Example 3

### Reading CSV **Files**

In [12]:
import pandas as pd

# Read the mtcars dataset
df = pd.read_csv("mtcars.csv")

# Display the first 5 rows
print(df.head())

               model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2  


## Pandas Example 4

### Descriptive **Statistics**

In [13]:
import pandas as pd

# Read Iris dataset
iris = pd.read_csv("Iris.csv")

# Display descriptive statistics
print(iris.describe())

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000


## Pandas Example 5

### Covariance **Matrix**

In [14]:
import pandas as pd

# Read Iris dataset
iris = pd.read_csv("Iris.csv")

# Calculate covariance matrix
print(iris.cov(numeric_only=True))

                        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             1887.500000      25.782886     -7.492282      67.667785   
SepalLengthCm    25.782886       0.685694     -0.039268       1.273682   
SepalWidthCm     -7.492282      -0.039268      0.188004      -0.321713   
PetalLengthCm    67.667785       1.273682     -0.321713       3.113179   
PetalWidthCm     29.832215       0.516904     -0.117981       1.296387   

               PetalWidthCm  
Id                29.832215  
SepalLengthCm      0.516904  
SepalWidthCm      -0.117981  
PetalLengthCm      1.296387  
PetalWidthCm       0.582414  


## Pandas Example 6

### Correlation **Matrix**

In [15]:
import pandas as pd

# Read Iris dataset
iris = pd.read_csv("Iris.csv")

# Calculate correlation matrix
print(iris.corr(numeric_only=True))

                     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             1.000000       0.716676     -0.397729       0.882747   
SepalLengthCm  0.716676       1.000000     -0.109369       0.871754   
SepalWidthCm  -0.397729      -0.109369      1.000000      -0.420516   
PetalLengthCm  0.882747       0.871754     -0.420516       1.000000   
PetalWidthCm   0.899759       0.817954     -0.356544       0.962757   

               PetalWidthCm  
Id                 0.899759  
SepalLengthCm      0.817954  
SepalWidthCm      -0.356544  
PetalLengthCm      0.962757  
PetalWidthCm       1.000000  
